---

all:
  vars:
    ansible_user: cloud_user
    # ansible_password: p@sswd1234
  # hosts:
  #   controller:
  #     ansible_host: 023d2663ed1c.mylabserver.com
  children:
    controller:
      hosts:
        controller-1:
          ansible_host: c377467d971c.mylabserver.com
    worker:
      hosts:
        worker-1:
          ansible_host: ac7d610b5e1c.mylabserver.com
        worker-2:
          ansible_host: 9f0eeaaa191c.mylabserver.com
  #       two.example.com:
  #       three.example.com:
