---

all:
  vars:
    ansible_user: admin
    # ansible_user: ubuntu
    # ansible_password: p@sswd1234
  # hosts:
  #   controller:
  #     ansible_host: 023d2663ed1c.mylabserver.com
  children:
  #  controller:
  #    hosts:
  #      controller-1:
  #        ansible_host: c377467d971c.mylabserver.com
    worker:
      hosts:
        # worker-1:
        #   ansible_host: ec2-3-239-196-11.compute-1.amazonaws.com
        worker-2:
          ansible_host: ec2-44-199-254-245.compute-1.amazonaws.com
  #       two.example.com:
  #       three.example.com:
