---
# tasks file for install_crio

- name: Parse distro name to match the repo standards
  set_fact:
    parsed_os: "{{ distro + '_' + ansible_distribution_version }}"
    repo_base_url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable
  vars:
    distro: "{{ (ansible_distribution == 'Ubuntu') | ternary('x' + ansible_distribution, ansible_distribution) }}"

- name: Import repository keys
  apt_key:
    url: "{{ item }}"
    state: present
  with_items:
    - "{{ repo_base_url }}/{{ parsed_os }}/Release.key"

- name: Add repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "deb {{ repo_base_url }}/{{ parsed_os }}/ /"
    - "deb {{ repo_base_url }}:/cri-o:/{{ container_runtime_version }}/{{ parsed_os }}/ /"

- name: Install packages
  apt:
    name:
    - cri-o
    - cri-o-runc
    state: present
