---
# tasks file for install_crio

- when: ansible_distribution_version | float <= 10
  vars:
    repo_name: buster-backports
  block:
  - name: "Add {{ repo_name }} repository"
    apt_repository:
      repo: "deb http://deb.debian.org/debian {{ repo_name }} main"
      state: present
      update_cache: yes

  - name: "Install libseccomp2 from {{ repo_name }}"
    apt:
      name: libseccomp2
      default_release: "{{ repo_name }}"
      state: latest

  - name: "Remove {{ repo_name }} repository"
    apt_repository:
      repo: "deb http://deb.debian.org/debian {{ repo_name }} main"
      state: absent
      update_cache: yes

- include_tasks: "{{ ansible_os_family | lower }}-based.yml"
