---
# tasks file for install_crio

- name: Use distro-specific playbook
  include_tasks: "{{ lookup('first_found', find_me) }}"
  register: included
  vars:
    find_me:
      - "{{ ansible_distribution | lower }}.yml"
      - "{{ ansible_os_family | lower }}-based.yml"

- name: Configure cgroup driver
  copy:
    content: |
      [crio.runtime]
      conmon_cgroup = "pod"
      cgroup_manager = "cgroupfs"
    dest: /etc/crio/crio.conf.d/02-cgroup-manager.conf

- name: "Role conclusion ({{ role_hash_short }})"
  debug:
    var: included
  vars:
    role_hash_short: "{{ (role_name | hash('md5'))[:10] }}"
  changed_when: included is succeeded
  notify: "{{ role_hash_short }}/post_install"

- name: Flush handlers
  meta: flush_handlers
