---
# tasks file for install_containerd

- name: Install repository dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
    state: present

- name: Import repository key
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower}}/gpg"
    state: present

- name: Add repository
  apt_repository:
    repo: "deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower}} stable"
    state: present

- name: Install packages
  apt:
    name: "containerd.io={{ container_runtime_version }}"
    state: present
