---
# tasks file for install_containerd

- name: Use distro-specific playbook
  include_tasks: "{{ lookup('first_found', find_me) }}"
  register: included
  vars:
    find_me:
      files:
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}-based.yml"

- name: Create a configuration directory
  file:
    path: /etc/containerd
    state: directory

- name: Default configuration (1/3)
  command: containerd config default
  changed_when: false
  register: containerd_config

- name: Default configuration (2/3)
  copy:
    content: "{{ containerd_config.stdout }}"
    dest: /etc/containerd/config.toml

- name: Default configuration (3/3)
  replace:
    path: /etc/containerd/config.toml
    regexp: "systemd_cgroup(\\s+.*)$"
    replace: systemd_cgroup = true

- name: "Role conclusion ({{ role_hash_short }})"
  debug:
    var: included
  vars:
    role_hash_short: "{{ (role_name | hash('md5'))[:10] }}"
  changed_when: included is succeeded
  notify: "{{ role_hash_short }}/post_install"

# - name: Flush handlers
  meta: flush_handlers
