---
# tasks file for common

- name: Use distro-specific playbook
  include_tasks: "{{ lookup('first_found', find_me) }}"
  register: included
  vars:
    find_me:
      - "{{ ansible_distribution | lower }}.yml"
      - "{{ ansible_os_family | lower }}-based.yml"

- name: "Conclusion ({{ role_hash_short }})"
  debug:
    var: included
  vars:
    role_hash_short: "{{ (role_name | hash('md5'))[:10] }}"
  changed_when: included is succeeded
  notify: "{{ role_hash_short }}/post_install"

- meta: flush_handlers
