---
# tasks file for common

- name: Use distro-specific playbook
  include_tasks: "{{ lookup('first_found', find_me) }}"
  register: _included
  vars:
    find_me:
      - "{{ ansible_distribution | lower }}.yml"
      - "{{ ansible_os_family | lower }}-based.yml"

- name: Conclusion
  debug:
    var: role_hash_short
  vars:
    role_hash_short: "{{ (role_name | hash('md5'))[:10] }}"
  changed_when: _included is succeeded
  notify: "{{ role_hash_short }}/post_install"

- name: Flush handlers
  meta: flush_handlers
