---
# tasks file for prepare_os

- name: "Set hostname to match {{ inventory_file }}"
  hostname:
    name: "{{ inventory_hostname }}"

- name: Update hosts file
  lineinfile:
    dest: /etc/hosts
    line: "{{ ipv4_address }} {{ item }}"
    regexp: ".*{{ item }}$"
    state: present
  vars:
    ipv4_address: "{{ hostvars[item]['ansible_default_ipv4']['address'] | default(omit) }}"
  when: ipv4_address is defined
  with_items: "{{ play_hosts }}"

- name: Load modules
  copy:
    dest: /etc/modules-load.d/kubernetes.conf
    content: |
      br_netfilter
      overlay
    validate: xargs -a %s -n 1 modprobe -vv

- name: Set iptables properties
  copy:
    dest: /etc/sysctl.d/kubernetes.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables=1
      net.bridge.bridge-nf-call-iptables=1
      net.ipv4.ip_forward=1
    validate: xargs -a %s -n 1 sysctl -w

- name: Disable swap
  replace:
    path: /etc/fstab
    regexp: '^(\s*)([^#\n]+\s+)(\w+\s+)swap(\s+.*)$'
    replace: '#\1\2\3swap\4'
    backup: yes
    validate: swapoff -a

- name: Use distro-specific playbook
  include_tasks: "{{ lookup('first_found', find_me) }}"
  vars:
    find_me:
      - "{{ ansible_distribution | lower }}.yml"
      - "{{ ansible_os_family | lower }}-based.yml"
